Introduced a new internal util to preserve relative format
keras-team/keras-cv pull request #1016
Opened 2022-11-15 15:07 UTC by quantumalaviya

# What does this PR do?
Introduced a new internal util to preserve relative format

Discussed in #1006 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@LukeWood

2022-11-15 18:49 UTC, LukeWood requested changes
If easy, lets also add a ValueError to ensure that `bounding_box_format` is in the list of formats.  you can use the converter keys() for this.

It may be good to add 1-2 unit tests too.  Thanks!

2022-11-16 15:10 UTC, quantumalaviya commented
Sure, is there a list of supported `bounding_box_formats` declared somewhere in the repository? We wouldn't want to update this function every time a new format is added.

2022-11-17 16:53 UTC, quantumalaviya commented
@LukeWood please check out the new tests and the ValueError

2022-11-22 06:20 UTC, LukeWood approved these changes
Looks good, thanks!

2022-11-22 06:20 UTC, LukeWood commented on keras_cv/bounding_box/utils.py
> +def _preserve_rel(target_bounding_box_format, bounding_box_format):
can we remove the _ here and just export the function?

2022-11-22 06:21 UTC, LukeWood commented on keras_cv/bounding_box/iou.py
> +    target = bounding_box.utils._preserve_rel("yxyx", bounding_box_format)
when using the function lets actually specify the argument names:

```
 target = bounding_box.utils._preserve_rel(target_format="yxyx", bounding_box_format=bounding_box_format)
```

2022-11-27 18:49 UTC, quantumalaviya commented
@LukeWood Made the changes, please take a look now

2022-11-28 18:06 UTC, LukeWood commented
hey @quantumalaviya LGTM but tests are failing!

2022-11-28 18:20 UTC, LukeWood commented
/gcbrun

2022-11-28 18:23 UTC, merged