Remove closures Convnext
keras-team/keras-cv pull request #1432
Opened 2023-02-21 23:40 UTC by IMvision12

# What does this PR do?

fix : #1419
As convnext does not have weights yet, i have done comparison of total number of params [colab](https://colab.research.google.com/drive/11SSf4cHgOBBPinRchYdsJXTuXFm9Hour?usp=sharing)

@ianstenbit

2023-02-22 11:08 UTC, IMvision12 commented
Test file will be addressed by this PR #1389

2023-02-22 17:23 UTC, ianstenbit requested changes
Thank you! In your colab, can you also verify numerical equivalence for the two models?

(Just save the weights from one and load it into the other model and check that the outputs match)

2023-02-22 17:23 UTC, ianstenbit commented on keras_cv/models/convnext.py
> +    x1 = x
nit: maybe let's call this x0 or "inputs"

2023-02-22 17:23 UTC, ianstenbit commented on keras_cv/models/convnext.py
> +def Head(x, num_classes, activation="softmax", name=None):
Let's rename this to apply_head

2023-02-22 17:23 UTC, ianstenbit commented on keras_cv/models/convnext.py
> +      name: (Optional) name to pass to the model.  Defaults to "{name}".
Defaults to "convnext"

2023-02-22 17:49 UTC, IMvision12 commented
> (Just save the weights from one and load it into the other model and check that the outputs match)
We don't have weights for convnext

2023-02-22 17:51 UTC, ianstenbit commented
> > (Just save the weights from one and load it into the other model and check that the outputs match)
> > We don't have weights for convnext

Right -- randomly initialized weights are fine (just to verify that outputs match, they don't need to be good outputs)

2023-02-22 19:02 UTC, IMvision12 commented
Here : https://colab.research.google.com/drive/1UNLsPLS-lZrJ2mBv0PSJ_RiAHf8UVgt0?usp=sharing

2023-03-03 19:45 UTC, ianstenbit commented
> Here : https://colab.research.google.com/drive/1UNLsPLS-lZrJ2mBv0PSJ_RiAHf8UVgt0?usp=sharing

Updated your Colab a bit to also perform numerical equivalence testing for a sentinel input:
https://colab.research.google.com/gist/ianstenbit/fff6fa172e5a50ebfc72ceab2adb5f02/copy-of-convnext.ipynb

Looks good.

2023-03-03 19:46 UTC, ianstenbit commented
> Here : https://colab.research.google.com/drive/1UNLsPLS-lZrJ2mBv0PSJ_RiAHf8UVgt0?usp=sharing

Updated your Colab a bit to also perform numerical equivalence testing for a sentinel input:
https://colab.research.google.com/gist/ianstenbit/fff6fa172e5a50ebfc72ceab2adb5f02/copy-of-convnext.ipynb

Looks good.

2023-03-03 19:48 UTC, ianstenbit approved these changes
Looks good! 

I re-started the CI runs because they looked flaky. If the issue persists we can take another look.

2023-03-03 20:06 UTC, ianstenbit commented
/gcbrun

2023-03-03 20:47 UTC, merged