Make ViT a Function Subclass Model
keras-team/keras-cv pull request #1437
Opened 2023-02-22 14:24 UTC by cosmo3769

# What does this PR do?

Making ViT a Functional Subclass Model [WIP]

2023-03-06 15:07 UTC, ianstenbit requested changes
Thank you!
Colab looks good.

Just a few small changes and then we can merge!

2023-03-06 15:07 UTC, ianstenbit commented on keras_cv/models/vit.py
> +            "input_shape": self.input_shape,
This should be:

```
# Remove batch dimension from `input_shape`
"input_shape": self.input_shape[1:],
```

2023-03-06 15:07 UTC, ianstenbit commented on keras_cv/models/vit.py
> +            "classifier_activation": self.classifier_activation,
please also include 
```
"trainable": self.trainable,
```

2023-03-06 15:23 UTC, ianstenbit commented on keras_cv/models/vit.py
> +class ViT(keras.Model):
Please add
```
@keras.utils.register_keras_serializable(package="keras_cv.models")
```

2023-03-07 14:26 UTC, cosmo3769 commented on keras_cv/models/vit.py
> +            "input_shape": self.input_shape,
Added.

2023-03-07 14:26 UTC, cosmo3769 commented on keras_cv/models/vit.py
> +            "classifier_activation": self.classifier_activation,
Added

2023-03-07 14:26 UTC, cosmo3769 commented on keras_cv/models/vit.py
> +class ViT(keras.Model):
Added.

2023-03-07 14:28 UTC, cosmo3769 commented
Thank you for reviewing. I have made the necessary changes. Please check if it's good to go. @ianstenbit

2023-03-07 16:46 UTC, ianstenbit approved these changes
Thank you -- looks good!

2023-03-07 17:20 UTC, ianstenbit commented
@cosmo3769 Please take a look at the code format issue.

2023-03-07 21:42 UTC, cosmo3769 commented
> @cosmo3769 Please take a look at the code format issue.

Done.

2023-03-07 21:44 UTC, ianstenbit commented
/gcbrun

2023-03-07 22:37 UTC, merged