CSPDARKNET Subclassing
keras-team/keras-cv pull request #1478
Opened 2023-03-09 21:35 UTC by soma2000-lang

2023-03-14 14:14 UTC, ianstenbit requested changes
Thanks for the PR!

Let's also remove the closures from `darknet_utils`, and use the `apply_xyz` naming technique (this will also need to be done in #1486)

2023-03-14 14:14 UTC, ianstenbit commented on keras_cv/models/csp_darknet.py
> +    """This class Instantiates the CSPDarkNet architecture.
nit: s/Instantiates/represents

2023-03-14 14:14 UTC, ianstenbit commented on keras_cv/models/csp_darknet.py
> +    include_rescaling=None,
let's avoid including defaults here

2023-03-14 15:22 UTC, ID6109 commented
Hey @soma2000-lang , this is in reference to #1486 . I have already started working on `darknet_utils.py`, so how about I get back to you once I am through with the changes that can be incorporated into your PR? Thanks.

2023-03-14 15:29 UTC, soma2000-lang commented
Ok @ID6109 seems good

2023-03-14 15:50 UTC, ID6109 commented
@soma2000-lang I have made the necessary changes in `darknet_utils.py` but the tests are failing due to function name mismatches with `csp_darknet.py`. How about I go ahead with making the naming changes there as well? This might cause merge conflicts with your PR.

2023-03-14 15:53 UTC, soma2000-lang commented
@ID6109 let me make the name changes.
So that it does not cause the merge conflicts.Please tell me what name changes do you want to do

2023-03-14 16:04 UTC, soma2000-lang commented
@ID6109 I will do that

2023-03-16 14:42 UTC, ianstenbit commented
> Let's also remove the closures from `darknet_utils`, and use the `apply_xyz` naming technique (this will also need to be done in #1486)

Upon further inspection, let's _not_ update the layers in `darknet_utils` and instead leave them as-is.

So this PR is very close -- just the few small comments I left.

Additionally, let's test pre-trained weights in the Colab. `"imagenet"` weights are available for `CSPDarkNetL`

2023-03-16 20:11 UTC, ianstenbit approved these changes
Looks good -- just one more small fix and then we can merge :)

Your Colab no longer runs, but I was able to adapt it to make sure weight loading still works:
https://colab.research.google.com/gist/ianstenbit/b2ef30c13329624e45200008ce4acb46/cspdarknetm.ipynb

With respect to KerasIO guides -- right now, we're still a bit short on model offerings and we're still in the process of updating our API to unify with KerasNLP, so we're holding off on guides for`KerasCV` models. However, if there are models that we don't include in KerasCV (yet!), feel free to create guides on those, and we can use that as a starting point for introducing those models here.

2023-03-16 20:11 UTC, ianstenbit commented on keras_cv/models/csp_darknet.py
> +    include_top=None,
nit: please remove this default value of `include_top`

2023-03-16 20:11 UTC, ianstenbit commented
Also @soma2000-lang please take a look at the lint and test errors

2023-03-16 20:19 UTC, ianstenbit commented on keras_cv/models/csp_darknet.py
> +@keras.utils.regester_keras_serializable(package="keras_cv.models")
nit: s/regester/register

2023-03-17 16:15 UTC, ianstenbit commented
/gcbrun

2023-03-17 17:06 UTC, ianstenbit requested changes

2023-03-17 17:06 UTC, ianstenbit commented on keras_cv/models/csp_darknet.py
> +        return model
Sorry I missed this in the first review.

We shouldn't be `return`ing anything, as this is now a constructor.

We do need to set model-level properties, though, and add a `get_config` and `from_config`

See e.g. https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/regnet.py#L791 for an example of this

2023-03-20 16:55 UTC, merged