fixing
keras-team/keras-cv pull request #1495
Opened 2023-03-13 07:24 UTC by soma2000-lang

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2023-04-26 22:23 UTC, LukeWood approved these changes

2023-04-26 22:23 UTC, LukeWood commented
@soma2000-lang looks like this fails the lint.  Please run ./shell/format.sh

2023-04-26 22:23 UTC, LukeWood requested changes
Ah wait - unit tests actually fail.  

Please address all unit test failures before re-requesting review!

2023-04-27 05:22 UTC, james77777778 commented on keras_cv/layers/preprocessing/random_brightness.py
>      def augment_ragged_image(self, image, transformation, **kwargs):
Following should fix the issue:

```python
def augment_ragged_image(self, image, transformation, **kwargs):
    image = tf.expand_dims(image, axis=0)
    transformation = tf.expand_dims(transformation)
    image = self.augment_images(
        images=image, transformations=transformation, **kwargs
    )
    return tf.squeeze(image, axis=0)
```

2023-05-04 17:16 UTC, LukeWood commented
/gcbrun

2023-05-04 17:41 UTC, LukeWood commented
Thank you @soma2000-lang !

2023-05-09 18:43 UTC, LukeWood approved these changes

2023-05-09 18:43 UTC, merged