Migrate VIT [WIP]
keras-team/keras-cv pull request #1654
Opened 2023-04-03 00:27 UTC by soma2000-lang

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2023-04-03 15:10 UTC, jbischof reviewed
I don't think ViT will work as a backbone preset due to the very different structure from convolution models. We may need to omit from `backbone_presets` and build a custom classifier. I don't think feature pyramids will be compatible either. (cc @ianstenbit)

2023-04-18 08:05 UTC, soma2000-lang commented
@jbischof @jbischof  Should I omit the backbone presets then

2023-04-18 14:44 UTC, jbischof requested changes
Good start, now you need to rebase the class on `Backbone`

2023-04-18 14:44 UTC, jbischof commented on keras_cv/models/backbones/vit/vit_backbone.py
Good job using `git mv`, but you also need to rebase the code on the `Backbone` class.

2023-04-18 14:44 UTC, jbischof commented on keras_cv/models/backbones/vit/vit_backbone_presets.py
> +            "stackwise_filters": [64, 128, 256, 512],
This preset definitions still appear to be from the ResNet model. You can update once `ViTBackbone` is ready

2023-04-18 15:38 UTC, soma2000-lang commented
@jbischof will fo that

2023-05-15 23:20 UTC, jbischof commented
Closing since we don't want to move forward on this for now

2023-05-19 16:33 UTC, closed without merging