Effi
keras-team/keras-cv pull request #1718
Opened 2023-04-18 10:22 UTC by soma2000-lang

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
- [ ] Did you write any new necessary tests?
- [ ] If this adds a new model, can you run a few training steps on TPU in Colab to ensure that no XLA incompatible OP are used?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

2023-04-18 10:32 UTC, soma2000-lang commented
All  the lint tests of all my prs are failing due to this .Currently investigating why.
![image](https://user-images.githubusercontent.com/56045049/232750808-d147c378-8879-4479-9f17-3eb58fc2608a.png)

2023-04-18 15:10 UTC, jbischof commented
@soma2000-lang you just need to run `./shell/format.sh`

2023-04-18 15:31 UTC, ID6109 commented
Actually, this is likely due to a messy merge because line length issues are clearly extending beyond the files this PR intends to change. Refer to [this](https://github.com/keras-team/keras-cv/pull/1552).

2023-04-18 15:36 UTC, soma2000-lang commented
@jbischof I have runned that.still the same the lint is failing

2023-04-18 16:56 UTC, soma2000-lang commented
@jbischof @ID6109 The problem  is that I have not made changes  to those files (whose Lint is failing).I have used # noqa at 
places in my files and have runned shell/format.sh

2023-04-19 00:49 UTC, LukeWood commented on keras_cv/models/backbones/efficientnetv2/efficientnet_v2_backbone.py
>          width_coefficient,
@jbischof what do you want to do about things like "width_coefficient" and "depth_coefficient" that are generally only used by the wrapping classes?  We typically dont expect users to configure them; but I guess we just document them and leave them in?

2023-04-19 00:51 UTC, LukeWood commented on keras_cv/models/backbones/efficientnetv2/efficientnet_v2_backbone.py
> +        include_rescaling=True,
these subclasses should be passing the __init__ constructor of `super()` values for width_coefficient and and depth_coefficient.

See line 912 in the current file:

```

    return EfficientNetV2(
        include_rescaling=include_rescaling,
        include_top=include_top,
        width_coefficient=1.0,
        depth_coefficient=1.1,
        default_size=240,
        model_name="efficientnetv2-b1",
        weights=parse_weights(weights, include_top, "efficientnetv2b1"),
        input_shape=input_shape,
        input_tensor=input_tensor,
        pooling=pooling,
        num_classes=num_classes,
        classifier_activation=classifier_activation,
```

You'll want to preserve this!

2023-04-19 00:52 UTC, LukeWood requested changes
overall this looks quite good - there are just a few changes that need to be made.  Thanks @soma2000-lang !

2023-04-19 08:40 UTC, soma2000-lang commented
@jbischof @ID6109 The problem  is that I have not made changes  to those files (whose Lint is failing).I have used # noqa at 
places in my files and have runned shell/format.sh

2023-04-19 08:43 UTC, soma2000-lang commented
Hi @cosmo3769 you can collaborate but just a gentle request ,please dont open PRs for issues for which you can see pr already  is opened.

2023-04-24 18:39 UTC, closed without merging