Feat: Simple Copy-Paste Augmentation (Instance Segmentation)
keras-team/keras-cv pull request #175
Opened 2022-03-18 09:09 UTC by MrinalTyagi

# Description 

Feature Addition: Simple Copy-Paste Augmentation (Instance Segmentation)
References issue: #28 

POC: @innat @bhack 
Other mentions: @frostbyte012 -> Do look at the implementation template and try adding onto the PR after @innat @bhack approve the basic implementation. 

Comments added for more readability and understanding of @frostbyte012 and will at a later stage if not required. 

Thank for giving me a chance to contribute. :)

2022-03-18 15:36 UTC, innat commented
@MrinalTyagi I can't approve anything here. Only the keras team can. 

( Keep updating your PR until the keras team begins review. )

2022-03-18 15:59 UTC, frostbyte012 commented
@MrinalTyagi I'm looking into the implementation and will go on with the PR as I understand more about the implementation

2022-03-18 16:02 UTC, MrinalTyagi commented
@frostbyte012 You can continue adding to the same pr only rather than creating a new one.

2022-03-23 18:58 UTC, LukeWood requested changes

2022-03-23 18:58 UTC, LukeWood commented on keras_cv/layers/preprocessing/copy_paste.py
> +from skimage.filters import gaussian
yeah, we can't rely on albumerations, skimage, or cv2

2022-03-23 18:58 UTC, LukeWood commented
Thank you for your contribution @MrinalTyagi - lets try to get a pure TensorFlow implementation then we can continue with the review.  Thanks!

2022-04-02 12:16 UTC, MrinalTyagi commented
@LukeWood Sorry guys for not following up on this as really sick right now. Will soon pick up the task of refining the code to be enabled for merging.

2022-04-12 00:18 UTC, LukeWood commented
> @LukeWood Sorry guys for not following up on this as really sick right now. Will soon pick up the task of refining the code to be enabled for merging.

Don't worry about it.  Don't want to be any source of stress.  I appreciate the contribution none the less and follow up when you feel better!

2022-04-21 17:29 UTC, LukeWood commented
> @LukeWood Sorry guys for not following up on this as really sick right now. Will soon pick up the task of refining the code to be enabled for merging.

Hey @MrinalTyagi will you be returning to this?  If not,  I'll reopen so that another contributor can take it on.  No pressure or stress!

2022-04-24 10:51 UTC, MrinalTyagi commented
> > @LukeWood Sorry guys for not following up on this as really sick right now. Will soon pick up the task of refining the code to be enabled for merging.
> 
> Hey @MrinalTyagi will you be returning to this? If not, I'll reopen so that another contributor can take it on. No pressure or worries! Just want to make sure we move forward on this issue at some point!

Sorry for delay. I'm back on it. :)

2022-04-26 09:23 UTC, MrinalTyagi commented
> > > @LukeWood Sorry guys for not following up on this as really sick right now. Will soon pick up the task of refining the code to be enabled for merging.
> 
> > 
> 
> > Hey @MrinalTyagi will you be returning to this? If not, I'll reopen so that another contributor can take it on. No pressure or worries! Just want to make sure we move forward on this issue at some point!
> 
> 
> 
> Sorry for delay. I'm back on it. :)
> 
> 

Hi team. Got some issue with my laptop and have given it for repair. Please assign it to someone else. Sorry for being a blocker.

2022-05-06 19:58 UTC, frostbyte012 commented
@LukeWood , and @innat I'm trying this one soon next ! Looks like I'll create another new PR for this issue #28 instead of carrying on with this one.

2022-06-11 18:51 UTC, LukeWood commented
Closing as we haven't had any activity here and this depends on packages we can't use.

2022-06-11 18:51 UTC, closed without merging

2024-10-04 11:48 UTC, BuddhiAbeyratne commented
I understand not shipping this in Keras 
but is it possible for it to be a separate package or something @MrinalTyagi  maybe