Adding num_cutouts to RandomCutout
keras-team/keras-cv pull request #178
Opened 2022-03-20 15:26 UTC by quantumalaviya

Added `num_cutouts` parameter to `RandomCutout` as mentioned in issue #134 

Sample usage:
```python
(images, labels), _ = tf.keras.datasets.cifar10.load_data()
random_cutout = keras_cv.layers.preprocessing.RandomCutout(0.5, 0.5, num_cutouts = (10, 30))
augmented_images = random_cutout(images)
```
This cutout will add random cutouts in the range [10, 30]

2022-03-21 19:58 UTC, LukeWood requested changes
Nice work!  Thanks

2022-03-21 19:58 UTC, LukeWood commented on keras_cv/layers/preprocessing/random_cutout.py
> +        num_cutouts: One of:
add the default "Defaults to 1."

2022-03-21 19:58 UTC, LukeWood commented on keras_cv/layers/preprocessing/random_cutout.py
> +    def _compute_num_cutouts(self):
rename to `_sample_num_cutouts`

2022-03-21 20:27 UTC, LukeWood approved these changes

2022-03-21 20:27 UTC, LukeWood commented
Thanks @quantumalaviya !!!

2022-03-21 20:28 UTC, LukeWood requested changes

2022-03-21 20:28 UTC, LukeWood commented on keras_cv/layers/preprocessing/random_cutout.py
> +        for _ in range(self._sample_num_cutouts()):
Does this work with `tf.range` instead of `range`?

2022-03-21 20:28 UTC, parikshit14 commented
hi, but dont you think implementation should be in vectorized format

2022-03-21 20:28 UTC, parikshit14 commented
hi, but dont you think implementation should be in vectorized format

2022-03-21 20:33 UTC, parikshit14 commented
@LukeWood dont you think this will effect upon the overall performance as the techniques used are not in vectorized format and is simply using loops

2022-03-21 20:33 UTC, parikshit14 commented
@LukeWood dont you think this will effect upon the overall performance as the techniques used are not in vectorized format and is simply using loops

2022-03-21 20:50 UTC, merged

2022-03-21 20:50 UTC, LukeWood commented
> @LukeWood dont you think this will effect upon the overall performance as the techniques used are not in vectorized format and is simply using loops

I think we can rely on `BaseImageAugmentationLayer` to vectorize this.

2022-03-21 21:30 UTC, parikshit14 commented
I was able to complete the vectorized form so instead of just relying on `BaseImageAugmentationLayer` we can simply use the vectorized form at the very base, it will in one way or another give an edge, if you wanna have a look at the vectorized code I can create a PR for that!

2022-03-22 09:57 UTC, quantumalaviya commented
@parikshit14 I assume you're talking about vectorizing across the number of cutouts? Did you use `fill_utils` in your PR or drop the reference altogether? If you used it, you might have had to edit `fill_rectangle` as well?

2022-03-22 12:25 UTC, parikshit14 commented
> @parikshit14 I assume you're talking about vectorizing across the number of cutouts? Did you use `fill_utils` in your PR or drop the reference altogether? If you used it, you might have had to edit `fill_rectangle` as well?

yes, I did some changes in `fill_rectangle` as well as in `rectangle_masks` that's the reason it took me so long to get to the vectorized code.

2022-03-22 12:49 UTC, parikshit14 commented
@LukeWood I tried implementing the new benchmark(according to `num_cutouts` ) and looks like tf.range cannot be optimized by  `tf.vectorized_map` as it is giving error `OperatorNotAllowedInGraphError: Iterating over a symbolic 'tf.Tensor' is not allowed` .

Also did some benchmarks to compare vectorized vs non-vectorized approaches for `num_cutouts=5`. 
**Results :** 
![vectorized_vs_unvectorized](https://user-images.githubusercontent.com/54709254/159484411-84d03457-1a30-422e-9c70-f7eeefa2966f.png)

_UnvRandomCutout_ -> unvectorized approch
_VRandomCutout_ -> vectorized approch