Fixing conversion of box formats on the original boxes
keras-team/keras-cv pull request #2213
Opened 2023-12-06 03:50 UTC by ariG23498

Fixes #2201 

CC: @divyashreepathihalli

2023-12-08 22:49 UTC, divyashreepathihalli requested changes

2023-12-11 19:20 UTC, divyashreepathihalli commented
@ariG23498 I think we should update all the code where we are converting Bboxes in place too.

2023-12-17 14:17 UTC, ariG23498 commented
@divyashreepathihalli I think that is a good idea, do you think there is a good (efficient) way to find out such places in the code? If not, I could do that manually.

2023-12-27 09:58 UTC, divyashreepathihalli commented
Haha! we would have to do it manually. It is of a lower priority atm. I will go ahead and merge this PR for now and you can open a new PR for the rest of the code if you would like.

2023-12-27 09:58 UTC, divyashreepathihalli approved these changes

2023-12-27 18:15 UTC, merged