extend IOU test against official pycocotools
keras-team/keras-cv pull request #230
Opened 2022-03-28 15:40 UTC by bhack

This is going to temp check some low level utils comparing keras_cv results with the reference implementation. 

It will start with IOU but I don't if it is failing know cuase the bbox coords order are expressed differntly bettween keras_cv and the reference implementation.

https://github.com/keras-team/keras-cv/issues/222

Note: This is not going to be merged as it is going to be used as a public/shared debug session.

2022-03-28 17:13 UTC, LukeWood requested changes

2022-03-28 17:16 UTC, bhack commented on keras_cv/utils/iou_test.py
> +from pycocotools import mask as maskUtils
You don't need to merge this we need to use the library for public debug with the CI.

When it is solved we will remove the library as in the meantime we could scale on other components of the cocotools library.

2022-03-28 17:18 UTC, bhack commented
Can you kickoff the CI? Thanks.

2022-03-28 19:42 UTC, LukeWood commented
> Can you kickoff the CI? Thanks.

Done - thanks

2022-03-28 20:28 UTC, bhack commented
The single  IOU is non matching. Are the bbox coords expressed in the same format?

2022-03-28 22:03 UTC, LukeWood commented
> The single IOU is non matching. Are the bbox coords expressed in the same format?

I’m not sure the format cocoeval expects in this helper.  Want to try switching them? Our utility functions should help with that.

2022-03-29 04:41 UTC, LukeWood commented on keras_cv/utils/iou_test.py
> +from pycocotools import mask as maskUtils
So this all passes now and the ious are correct?

2022-03-29 04:41 UTC, LukeWood commented
@bhack we should merge a PR from you so that I don't have to approve your CI runs.  lets do it on one of the contribution guides or style guides - just make a dummy change (like one space after a sentence to two spaces or something).  I think then the CI run will automatically for you.

2022-03-29 04:48 UTC, LukeWood commented
maybe now that I committed it will auto run

2022-03-29 12:27 UTC, bhack commented on keras_cv/utils/iou_test.py
> +from pycocotools import mask as maskUtils
Yes have you maintained the original pycoco `x,y,w,h` format when you have generated the numerical testing sample in:
https://github.com/keras-team/keras-cv/blob/master/keras_cv/metrics/coco/numerical_tests/GenerateSamples.ipynb

Cause if you have maintained that format you cannot use the current keras-cv  conversion that you call in `load_sample` as MSCOCO is `x,y = top-left` and not the center of the bbox:
https://github.com/keras-team/keras-cv/blob/bef996fe091d42f4ed219b9273597d8d5676d01c/keras_cv/utils/bounding_box.py#L78-L97

Also is the area filtered with `>=` and `<=` or `>` and `<` ?
https://github.com/keras-team/keras-cv/blob/bef996fe091d42f4ed219b9273597d8d5676d01c/keras_cv/metrics/coco/utils.py#L22

Cause in the reference implementation I see  the detection filtered with `>=` and `<=`:
```python
# set unmatched detections outside of area range to ignore
a = np.array([d['area']<aRng[0] or d['area']>aRng[1] for d in dt]).reshape((1, len(dt)))

```
But in the annotation it seems filtered with `>` and `<`:
```python
 anns = anns if len(areaRng) == 0 else [ann for ann in anns if ann['area'] > areaRng[0] and ann['area'] < areaRng[1]]
```

2022-03-30 23:54 UTC, LukeWood commented
@bhack any update here - or extra thoughts on what we might want to do?

2022-03-31 00:20 UTC, bhack commented
@LukeWood Yes, probably you missed  my 2 days old message: 
https://github.com/keras-team/keras-cv/pull/230#discussion_r837414155

2022-03-31 17:40 UTC, LukeWood commented
> @LukeWood Yes, probably you missed my 2 days old message: [#230 (comment)](https://github.com/keras-team/keras-cv/pull/230#discussion_r837414155)

Ah yes - I did miss this.  Thanks.  I anticipate the `<=` and `<` difference will be very small and rare - but can try to make them match.  Per the bounding box format: I will check that they are equivalent.

2022-03-31 18:03 UTC, bhack commented
But have you seen the main point about bbox format?

2022-04-21 17:35 UTC, LukeWood commented
> It will start with IOU but I don't if it is failing know cuase the bbox coords order are expressed differntly bettween keras_cv and the reference implementation.

I did in fact verify that the format difference is taken into account.

2022-04-21 18:12 UTC, LukeWood commented
Performing an issue and PR triage now, can we close this?  It looks like this passes and iou is not in fact the issue.

2022-04-21 19:28 UTC, bhack commented
If you think that the the missing sorting is the last bug you could close this. Instead If there are other potential bugs that we need to check hand to hand against cocoeval subcomponents I think It Is still useful.

2022-04-21 21:49 UTC, LukeWood commented
>  If you think that the the missing sorting is the last bug you could close this. Instead If there are other potential bugs that we need to check hand to hand against cocoeval subcomponents I think It Is still useful.


sounds great.  Thanks for pointing out the sorting issue.  I think this is the only discrepancy remaining.

2022-04-21 21:49 UTC, closed without merging