Gaussian blur approval
keras-team/keras-cv pull request #262
Opened 2022-04-03 18:58 UTC by artu1999

pull request with correct author email

2022-04-04 05:29 UTC, LukeWood commented
Thanks for fixing!  Can review tomorrow!

2022-04-04 22:27 UTC, LukeWood commented on keras_cv/layers/preprocessing/gaussian_blur.py
> +        kernel_size: int, 2 element tuple or 2 element list. x and y dimensions for
Check out how we are handling sampling like this.  `sigma` could use this.  There is a nice utility to parse these ranges for you.  See https://github.com/keras-team/keras-cv/pull/238

This isn't merged yet - but you can rebase on the branch `factor` to use this.

2022-04-04 22:29 UTC, LukeWood requested changes

2022-04-04 22:29 UTC, LukeWood commented on keras_cv/layers/preprocessing/gaussian_blur.py
> +        sigma = self._random_generator.random_uniform(
Nicely done!

2022-04-04 22:29 UTC, LukeWood commented on keras_cv/layers/preprocessing/gaussian_blur_test.py
> +    def test_non_square_images(self):
Lets also implement a numerical test.  In order to do this, you can pass `sigma=(0.3, 0.3)` and compute desired output values for a given image.  For this image, may I recommend:

```
0 0 0
0 1 0
0 0 0
```

Then you can check what the values are on for the 0s, and ensure the filter is correctly applied.  Looking really good!

2022-04-04 22:29 UTC, LukeWood commented
@artu1999 thanks for the PR!  This is looking really good!  I left some minor comments - biggest one is adding the new test case!

2022-04-20 21:33 UTC, artu1999 commented
@LukeWood Still getting problems with the CLA agreement... the email in my config is the one of the contract, not sure why this is happening

2022-04-20 21:43 UTC, LukeWood commented
> @LukeWood Still getting problems with the CLA agreement... the email in my config is the one of the contract, not sure why this is happening

Can you accept it with your other email?  It is probably the author of one of your commits.

2022-04-20 22:00 UTC, artu1999 commented
> > @LukeWood Still getting problems with the CLA agreement... the email in my config is the one of the contract, not sure why this is happening
> 
> Can you accept it with your other email? It is probably the author of one of your commits.
 
I checked the CLA and it's the email github gave to my laptop, so I can't verify and sign the email. I was sure I changed it last time to the email in the CLA when I got the checks right, apologies for the mess. Could it help if I push from another branch and I double check before the PR that the email is set right?

2022-04-21 02:39 UTC, LukeWood commented
> > > @LukeWood Still getting problems with the CLA agreement... the email in my config is the one of the contract, not sure why this is happening
> > 
> > 
> > Can you accept it with your other email? It is probably the author of one of your commits.
> 
> I checked the CLA and it's the email github gave to my laptop, so I can't verify and sign the email. I was sure I changed it last time to the email in the CLA when I got the checks right, apologies for the mess. Could it help if I push from another branch and I double check before the PR that the email is set right?

Feel free to push to another branch with a single commit authored by the right email!  No worries @artu1999 these things can be a pain!

2022-04-21 17:38 UTC, closed without merging