Random jpeg quality preprocessing layer
keras-team/keras-cv pull request #342
Opened 2022-04-21 18:38 UTC by artu1999

See #135. Applies random jpeg compression artifcats to an image to induce noise.

2022-04-21 21:29 UTC, LukeWood requested changes

2022-04-21 21:29 UTC, LukeWood commented on keras_cv/layers/__init__.py
> -from keras_cv.layers.preprocessing.channel_shuffle import ChannelShuffle
revert spurious changes

2022-04-21 21:29 UTC, LukeWood commented on keras_cv/layers/preprocessing/gaussian_blur.py
> +class GaussianBlur(layers.Layer):
Looks like you need to rebase on origin/master

```
git fetch origin
git rebase origin/master -x theirs
```

2022-04-21 21:30 UTC, LukeWood commented
@artu1999 thanks for the PR!  Please rebase on the latest origin/master!

2022-05-10 01:03 UTC, Ashwin-Ravi commented
@artu1999 Following up to see if you would be returning to the PR?
I could take over, in case you would not be available to work on this.

2022-05-10 09:36 UTC, artu1999 commented
> @artu1999 Following up to see if you would be returning to the PR? I could take over, in case you would not able to return to this.

@Ashwin-Ravi @LukeWood I had a couple of hectic weeks with my dissertation lately, but I'm submitting it in two days, I will return on the PR straight after that!

2022-05-11 05:23 UTC, LukeWood commented
> > @artu1999 Following up to see if you would be returning to the PR? I could take over, in case you would not able to return to this.
> 
> @Ashwin-Ravi @LukeWood I had a couple of hectic weeks with my dissertation lately, but I'm submitting it in two days, I will return on the PR straight after that!

awesome, thanks for letting us know @artu1999.  Good luck on your dissertation!

2022-06-11 18:51 UTC, LukeWood commented
Closing in favor of your newer PR.

2022-06-11 18:51 UTC, closed without merging