Hausdorff loss
keras-team/keras-cv pull request #414
Opened 2022-05-05 15:08 UTC by blackhat-coder

issue [330](https://github.com/keras-team/keras-cv/issues/330)

Hausdorff distance is the maximum distance of a set to the nearest point in the other set.

![Capture](https://user-images.githubusercontent.com/57095771/166952919-058424e1-fc15-48d7-93a8-4d1ba0ce9df0.JPG)

Other variations of hausdorff distance include [weighted hausdorff distance](https://arxiv.org/pdf/1806.07564.pdf)

2022-11-11 17:11 UTC, tanzhenyu commented
@blackhat-coder can you help us describe how this will be used? And more importantly, which paper uses this loss that improves model quality

2023-01-05 21:06 UTC, bhack commented
@tanzhenyu  https://paperswithcode.com/paper/weighted-hausdorff-distance-a-loss-function

Also check https://paperswithcode.com/paper/weighted-hausdorff-distance-a-loss-function

2023-01-06 17:47 UTC, tanzhenyu requested changes

2023-01-06 17:47 UTC, tanzhenyu commented on keras_cv/losses/hausdorff_test.py
> +class HausdorffTest(tf.test.TestCase):
can you add a test with a fully convolutional network that compiles with this loss?

2023-04-26 21:53 UTC, LukeWood commented
Thanks for the PR!  For now we're going to limit contributions to things on our critical path; it is not clear to me that this loss independently produces value for users.  We will definitely revisit this loss should a model architecture that makes use of this loss be introduced to the package.

Perhaps if this is a standalone loss that provides great value it could belong in core Keras; but we'd need to discuss what unique issue this loss solves.

Feel free to discuss on the issue thread if you would really like to see this loss introduced!

2023-04-26 21:53 UTC, closed without merging