Added EfficientNet models
keras-team/keras-cv pull request #570
Opened 2022-07-10 01:49 UTC by ayyucedemirbas

# What does this PR do?

Fixes # ([issue](https://github.com/keras-team/keras-cv/issues/520))
Added EfficientNet models

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case. https://github.com/keras-team/keras-cv/issues/520
- [ ] Did you write any new necessary tests?

@LukeWood @tanzhenyu

2022-07-14 17:57 UTC, LukeWood requested changes

2022-07-14 17:57 UTC, LukeWood commented on keras_cv/models/efficientnet.py
> +    include_top: Whether to include the fully-connected
docstring should match the new API - please update arguments

2022-07-14 17:57 UTC, LukeWood commented on keras_cv/models/efficientnet.py
> +          'imagenet' (pre-training on ImageNet),
"imagenet" only will work if we have the right normalization technique included

2022-07-14 17:57 UTC, LukeWood commented on keras_cv/models/efficientnet.py
> +    input_shape = imagenet_utils.obtain_input_shape(
please update the code patterns to match those in keras_cv/models/

2022-07-19 12:27 UTC, ayyucedemirbas commented
Thank you so much! All done!

2022-09-10 20:40 UTC, LukeWood commented
Closed in lieu of https://github.com/keras-team/keras-cv/pull/740

2022-09-10 20:40 UTC, closed without merging