Added InceptionV3
keras-team/keras-cv pull request #580
Opened 2022-07-12 22:58 UTC by ayyucedemirbas

# What does this PR do?
Added InceptionV3

Fixes #571  

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/keras-team/keras-cv/blob/master/.github/CONTRIBUTING.md),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue? Please add a link
      to it if that's the case.
       https://github.com/keras-team/keras-cv/issues/571
- [ ] Did you write any new necessary tests?

## Who can review?

 @LukeWood @tanzhenyu @sayakpaul

2022-07-13 16:18 UTC, LukeWood requested changes
Thanks for the PR!

please update the API and code style to match keras_cv.models (no input_tensor, include_rescaling as an argument, include_top as required, no channels_first support, etc.)

After doing this we can do a full review.

2022-07-13 16:18 UTC, LukeWood commented on keras_cv/models/inception_v3.py
> +from tensorflow.python.util.tf_export import keras_export
remove keras_export

2022-07-13 16:18 UTC, LukeWood commented on keras_cv/models/inception_v3.py
> +layers = VersionAwareLayers()
don't need version aware layers in KerasCV

2022-07-13 16:18 UTC, LukeWood commented on keras_cv/models/inception_v3.py
> +def InceptionV3(
please update the API to match the example set in DenseNet.  there are distinctions between keras.applications and keras_cv.models:

https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/densenet.py

2022-07-13 20:20 UTC, ayyucedemirbas commented
Thanks, @LukeWood ! All solved!

2022-11-11 16:57 UTC, tanzhenyu reviewed
Thanks for the PR!

2022-11-11 16:57 UTC, tanzhenyu commented on keras_cv/models/inception_v3.py
> +def InceptionV3(
can you add unit test for the model?

2022-11-11 16:57 UTC, tanzhenyu commented on keras_cv/models/inception_v3.py
> +    if weights is not None:
can you try this model with the basic_training script we have today, and report the result?

2023-04-26 21:57 UTC, closed without merging