Utilities for handling Run-length-encoded Segmentation Maps
keras-team/keras-cv pull request #589
Opened 2022-07-16 09:43 UTC by soumik12345

# Utilities Added

- A function `rle_to_mask2d` is added that converts a Run-length encoded segmentation map to a 2-dimensional segmentation map. This function was adapted from [this StackOverflow answer](https://stackoverflow.com/a/58842473/8209968).
- A function `mask2d_to_rle` is added that converts a 2-dimensional segmentation map to a Run-length encoded segmentation map.

**Demo Notebook:** https://colab.research.google.com/drive/17ilyBukuAwwG1h7paB-JCGPmKP2zBqoV?usp=sharing

PR related to https://github.com/keras-team/keras-cv/issues/533 and https://github.com/keras-team/keras-cv/issues/327

CC: @LukeWood @tanzhenyu @sayakpaul @innat [@ayulockin](https://github.com/ayulockin)

2022-08-22 14:52 UTC, soumik12345 commented
CC: @sayakpaul

2022-08-22 14:58 UTC, sayakpaul requested changes
@soumik12345 please include a test script as well. 

@LukeWood to do another pass.

2022-08-22 14:58 UTC, sayakpaul commented on keras_cv/utils/rle_utils.py
> +import numpy as np
Must be included with a license.

Example: https://github.com/keras-team/keras-cv/blob/master/keras_cv/layers/preprocessing/aug_mix.py#L1-#L13

2022-08-22 14:58 UTC, sayakpaul commented on keras_cv/utils/rle_utils.py
> +def rle_to_mask2d(mask_rle: str, shape) -> tf.Tensor:
We're not using type annotation at the moment.

2022-08-22 14:58 UTC, sayakpaul commented on keras_cv/utils/rle_utils.py
> +    """
Include:

* A `Raises` flag (example) that discusses a corner case if that's known. 
* A sample example.

2022-08-22 14:58 UTC, sayakpaul commented on keras_cv/utils/rle_utils.py
> +    s = tf.strings.to_number(s, tf.int64)
When code-blocks are grouped please separate them with spaces.

2022-08-22 14:58 UTC, sayakpaul commented on keras_cv/utils/rle_utils.py
> +    """
Same. 

Include:

* `Raises` flag. 
* Sample usage.

2022-11-11 16:51 UTC, tanzhenyu reviewed
Thanks for the PR!

2022-11-11 16:51 UTC, tanzhenyu commented on keras_cv/utils/rle_utils.py
> +def rle_to_mask2d(mask_rle, shape):
please add unit tests for these 2 functions

2023-03-07 20:40 UTC, LukeWood commented
Closing for now.  We may revisit this someday in the future, but for now we need to design an API for segmentation maps.

2023-03-07 20:40 UTC, closed without merging