Fix docstring for compute_ious_for_image util
keras-team/keras-cv pull request #598
Opened 2022-07-19 18:32 UTC by quantumalaviya

# What does this PR do?

This fixes the docstring for compute_ious_for_image util.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@LukeWood

2022-07-19 18:35 UTC, quantumalaviya commented
Moreover, it may be a good idea for this util to support the bounding box API.

@LukeWood What do you think?

2022-07-21 17:41 UTC, LukeWood commented
A better solution to this would be to make this utility take a `bounding_box_format` argument.

2022-07-22 14:50 UTC, quantumalaviya commented
@LukeWood updated this PR to fix #605

2022-07-22 17:32 UTC, LukeWood requested changes
minor changes, but looks good to me otherwise!

2022-07-22 17:32 UTC, LukeWood commented on keras_cv/bounding_box/iou.py
> +      bounding_box_format: a case-sensitive string which is one of `"xyxy"`,
case-insensitive*

2022-07-22 17:32 UTC, LukeWood commented on keras_cv/bounding_box/iou.py
> +    if "rel" in bounding_box_format:
a comment explaining this would be helpful to future readers

2022-07-22 17:57 UTC, quantumalaviya commented on keras_cv/bounding_box/iou.py
> +      bounding_box_format: a case-sensitive string which is one of `"xyxy"`,
fixed this for nms as well!

2022-07-22 18:50 UTC, LukeWood commented on keras_cv/bounding_box/iou.py
> +def compute_ious_for_image(boxes1, boxes2, bounding_box_format):
let's rename this to `compute_iou()`

let's also introduce batched support to this now that this is a utility.  Feel free to do batched support using map_fn, performance is not a huge concern for batched ATM, mainly concerned about API consistency.

2022-07-22 18:50 UTC, LukeWood requested changes
minor change, apologies for late changes

2022-07-26 19:42 UTC, merged