Porting EfficientNets to KerasCV
keras-team/keras-cv pull request #625
Opened 2022-07-27 10:05 UTC by AdityaKane2001

@sayakpaul @LukeWood @ianjjohnson 

Ported over EfficientNets (V1 and V2) from keras. Made changes wherever necessary to stick to the KerasCV code style.

/auto Closes #551

2022-07-27 10:24 UTC, AdityaKane2001 commented
@LukeWood 

The test process was killed: 
![image](https://user-images.githubusercontent.com/64411306/181224819-852fe96a-c167-47ca-a7f9-8de53f7bcb1e.png)

2022-07-27 12:47 UTC, innat commented
There is already an active PR for eff-v1. 
https://github.com/keras-team/keras-cv/pull/570

2022-08-25 16:38 UTC, LukeWood commented
@AdityaKane2001 try rebasing this PR!

2022-08-25 16:40 UTC, LukeWood commented on keras_cv/models/efficientnet_v1.py
> +        num_classes: optional number of num_classes to classify images
we renamed `num_classes` to `classes` recently for API consistency, lets make that change here!

2022-08-25 23:33 UTC, LukeWood requested changes
Overall, looks great!  Just a minor nit or two... :)

2022-08-25 23:33 UTC, LukeWood commented on keras_cv/models/efficientnet_v1.py
> +    if weights and not tf.io.gfile.exists(weights):
please use:

https://github.com/keras-team/keras-cv/blob/master/keras_cv/models/weights.py#L17

now!

2022-08-29 09:06 UTC, closed without merging