Update COCOBase to support merge_state
keras-team/keras-cv pull request #80
Opened 2022-02-01 22:07 UTC by LukeWood

This will support TFMA's needs

2022-02-02 23:03 UTC, qlzh727 requested changes

2022-02-02 23:03 UTC, qlzh727 commented on keras_cv/metrics/coco/base_test.py
> +        self.assertEqual(0.0, metric_result.true_positives[0, 0].numpy())
if the weights shape is [1, 1], then let's change the assert here to be [[0.0]] and metric_result.true_positives

2022-02-02 23:03 UTC, qlzh727 commented on keras_cv/metrics/coco/base_test.py
> +        self.assertEqual(3.0, metric_result.false_positives[0, 0].numpy())
same. [[3.0]] and metric_result.false_positives

2022-02-02 23:03 UTC, qlzh727 commented on keras_cv/metrics/coco/base_test.py
> +        self.assertEqual(3.0, metric_result.false_positives[0, 0].numpy())
How about ground_truth_boxes?

2022-02-02 23:03 UTC, qlzh727 commented on keras_cv/metrics/coco/base.py
> +                assign_add_ops.append(weight.assign_add(weight_to_add))
I think we should check the shape of the weights, so that we don't accidentally broadcast the weights and produce wrong results.

2022-02-03 20:26 UTC, LukeWood commented on keras_cv/metrics/coco/base.py
> +        return [self.true_positives, self.false_positives, self.ground_truth_boxes]
Updated to be `_mergeable_weights`

2022-02-03 20:26 UTC, LukeWood commented on keras_cv/metrics/coco/base.py
> +            if len(self.mergeable_weights) != len(metric.mergeable_weights):
yeah, let's not expose this I agree.

2022-02-03 22:45 UTC, LukeWood commented
Closing in favor of PR 99 (99)

2022-02-03 22:45 UTC, closed without merging